import React from 'react';
import {render} from 'react-dom';


var Agreement = React.createClass({


    render: function () {
        var contains = null;
        contains =
            <div style={{padding: '70px'}}>
                <div id="register-container">
                    <h2 style={{textAlign: 'center'}}>Términos y condiciones de uso del Sitio</h2>
                    <h4 style={{textAlign: "center"}}>Contrato vigente a partir del 15 de octubre de 2015</h4>
                    <p>Este contrato describe los términos y condiciones generales (los "Términos y Condiciones Generales") aplicables al uso de los servicios ofrecidos por Sistema Operativo Supnuevo S.R.L.en adelante
                        <strong><strong>S.O.S.srl</strong></strong>
                        , ("los Servicios") dentro de los sitios www.supnuevo.com.ar. Cualquier persona (en adelante "Usuario" o en plural "Usuarios") que desee acceder y/o usar el sitio o los Servicios podrá hacerlo sujetándose a los Términos y Condiciones Generales respectivos, junto con todas las demás políticas y principios que rigen
                        <strong><strong>S.O.S.srl</strong></strong> y que son incorporados al presente por referencia.
                    </p>
                    <p><strong>TODA PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.</strong></p>
                    <p>El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de Privacidad así como en los demás documentos incorporados a los mismos por referencia, previo a su registración como Usuario de S.O.S. srl</p>
                    <p><strong>I - Capacidad</strong></p>
                    <p>Los Servicios sólo están disponibles para personas que tengan capacidad legal para contratar. No podrán utilizar los servicios las personas que no tengan esa capacidad, los menores de edad o Usuarios de <strong><strong>S.O.S.srl</strong></strong> que hayan sido suspendidos temporalmente o inhabilitados definitivamente. Si está registrando un Usuario como Empresa, debe tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de este Acuerdo.</p>
                    <p><strong>II - Registración</strong></p>
                    <p>Es obligatorio completar el formulario de registración en todos sus campos con datos válidos para poder utilizar los servicios que brinda <strong><strong>S.O.S.srl</strong></strong>. El futuro Usuario deberá completarlo con su información personal de manera exacta, precisa y verdadera ("Datos Personales") y asume el compromiso de actualizar los Datos Personales conforme resulte necesario. <strong><strong>S.O.S.srl</strong></strong> podrá utilizar diversos medios para identificar a sus Usuarios, pero <strong><strong>S.O.S.srl</strong></strong> NO se responsabiliza por la certeza de los Datos </p>
                    <p>Personales provistos por sus Usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados</p>
                    <p>El Usuario accederá a su cuenta personal ("Cuenta") mediante el ingreso de su Apodo y clave de seguridad personal elegida ("Clave de Seguridad"). El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad.</p>
                    <p>La Cuenta es personal, única e intransferible, y está prohibido que un mismo Usuario registre o posea más de una Cuenta. En caso que <strong><strong>S.O.S.srl</strong></strong> detecte distintas Cuentas que contengan datos coincidentes o relacionados, podrá cancelar, suspender o inhabilitarlas.</p>
                    <p>El Usuario será responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma está restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario. El Usuario se compromete a notificar a <strong><strong>S.O.S.srl</strong></strong> en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión o transferencia de la Cuenta bajo ningún título.</p>
                    <p><strong><strong><strong>S.O.S.srl</strong></strong></strong> se reserva el derecho de rechazar cualquier solicitud de registración o de cancelar una registración previamente aceptada, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.</p>
                    <p><strong>III - Modificaciones del Acuerdo</strong></p>
                    <p><strong><strong>S.O.S.srl</strong></strong> podrá modificar los Términos y Condiciones Generales en cualquier momento haciendo públicos en el Sitio los términos modificados. Todos los términos modificados entrarán en vigor a los 10 (diez) días de su publicación. Dentro de los 5 (cinco) días siguientes a la publicación de las modificaciones introducidas, el Usuario deberá comunicar por e-mail si no acepta las mismas; en ese caso quedará disuelto el vínculo contractual y será inhabilitado como Usuario siempre que no tenga deudas pendientes. Vencido este plazo, se considerará que el Usuario acepta los nuevos términos y el contrato continuará vinculando a ambas partes.</p>
                    <p><strong>IV - Listado de Bienes</strong></p>
                    <p><strong>IV.1 Publicación de bienes y/o servicios</strong></p>
                    <p>El Usuario/vendedor deberá ofrecer a la venta los bienes y/o  servicios en las categorías correspondientes. Las publicaciones deberán incluir textos descriptivos, gráficos, fotografías y otros contenidos y condiciones pertinentes para la venta del bien y/o servicio, siempre que no violen ninguna disposición de este acuerdo o demás políticas de <strong>S.O.S.srl</strong>.</p>
                    <p> Los productos ofrecidos por el Usuario Vendedor debe ser exactamente descriptos en cuanto a sus condiciones y características relevantes. Se entiende y presume que mediante la inclusión del bien o servicio en <strong>S.O.S.srl</strong>, el Usuario acepta que tiene la intención y el derecho de vender el/los bien/es por él ofrecido, o está facultado para ello por su titular y lo tiene disponible para su entrega inmediata. Se establece que los precios de los productos publicados deberán ser expresados con IVA incluido cuando corresponda la aplicación del mismo, y en moneda del curso legal. <strong>S.O.S.srl</strong> podrá remover cualquier publicación cuyo precio no sea expresado de esta forma para evitar confusiones o malos entendidos en cuanto al precio final del producto. En caso que se infrinja cualquiera de las disposiciones establecidas en esta cláusula <strong>S.O.S.srl</strong> podrá editar el espacio, solicitar al Usuario que lo edite, o dar de baja la publicación donde se encuentre la infracción y en ningún caso se devolverán o bonificarán los cargos de publicación.</p>
                    <p><strong>IV.2 Inclusión de imágenes y fotografías</strong></p>
                    <p>El usuario puede incluir imágenes y fotografías del producto ofrecido siempre que las mismas se correspondan con el artículo, salvo que se trate de bienes o productos o de servicios que por su </p>
                    <p><strong>S.O.S.srl</strong> podrá impedir la publicación de la fotografía, e incluso del producto, si interpretara, a su exclusivo criterio, que la imagen no cumple con los presentes Términos y Condiciones.</p>
                    <p><strong>IV.3 Artículos Prohibidos</strong></p>
                    <p>Sólo podrán ser ingresados en las listas de bienes ofrecido y/o servicios, aquellos cuya venta no se encuentre tácita o expresamente prohibida en los Términos y Condiciones Generales y demás políticas de <strong>S.O.S.srl</strong> o por la ley vigente.</p>
                    <p><strong>IV.4 Protección de Propiedad Intelectual</strong></p>
                    <p><strong>S.O.S.srl</strong> no se hace responsable respecto de la propiedad intelectual que los usuarios pudieran eventualmente invocar, reclamar, ceder o comercializar, ya que no es éste el sitio ni el espacio. </p>
                    <p><strong>V - Privacidad de la Información</strong></p>
                    <p>Para utilizar los Servicios ofrecidos por <strong>S.O.S.srl</strong>, los Usuarios deberán facilitar determinados datos de carácter personal. Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y </p>
                    <p><strong>VI - Obligaciones de los Usuarios</strong></p>
                    <p><strong>VI.1 Obligaciones del Comprador</strong></p>
                    <p>Durante el plazo fijado por el Usuario Comprador, los Usuarios  interesados podrán realizar  consultas de precios  de compra para los bienes y podrán contactar a los oferentes de los servicios. También podrán emitir pedidos ya sea basándose en los precios que previamente los vendedores hayan subido a S.O.S. srl. o aprobando las cotizaciones que los vendedores hayan enviado por medio de las consultas respondidas. La oferta de compra se cierra una vez que vence el plazo o se acaban las cantidades estipuladas por el Vendedor y la promoción del servicio culmina con el vencimiento del plazo de la publicación.</p>
                    <p>El Comprador está obligado a  comunicarse con el vendedor que haya seleccionado y completar la operación de compra</p>
                    <p>Al ofertar por una Nota de Pedido el Usuario acepta quedar obligado por las condiciones de venta incluidas en la descripción de los artículos en la medida en que las mismas no infrinjan las leyes o los Términos y Condiciones Generales y demás políticas de <strong>S.O.S.srl</strong>. La oferta de compra es irrevocable salvo en circunstancias excepcionales.</p>
                    <p>Las ofertas de compra sólo serán consideradas válidas, una vez que hayan sido procesadas por el sistema informático de <strong>S.O.S.srl</strong>.</p>
                    <p><strong>Impuestos</strong>. Tal como lo establece la normativa fiscal vigente, el comprador debe exigir factura o ticket al vendedor como comprobante de la operación. </p>
                    <p><strong>VI.2. Obligaciones del Vendedor</strong></p>
                    <p>El usuario vendedor debe tener capacidad legal para vender el/los bien/es objeto/s de su oferta. Si el usuario vendedor ha recibido  una consulta sobre los productos que previamente informó como que comercializa, queda obligado a comunicarse con el comprador por medio de responder consultas y completar la operación con el usuario comprador. Solamente en casos excepcionales el vendedor podrá retractarse de la venta, tales como cuando no haya podido acordar con el usuario comprador sobre la forma de pago, de entrega o no sea posible verificar la verdadera identidad o demás información del comprador.</p>
                    <p>Dado que S.O.S. srl es un punto de encuentro entre comprador y vendedor y no participa de las operaciones que se realizan entre ellos, el Vendedor será responsable por todas las obligaciones y cargas impositivas que correspondan por la venta de sus artículos, sin que pudiera imputársele a <strong>S.O.S.srl</strong> algún tipo de responsabilidad por incumplimientos en tal sentido.</p>
                    <p><strong>Impuestos</strong>. Como se menciona anteriormente, <strong>S.O.S.srl</strong> sólo pone a disposición de los usuarios un espacio virtual que les permite comunicarse mediante Internet para encontrar una forma de vender o comprar artículos y/o servicios. <strong>S.O.S.srl</strong> no tiene participación alguna en el proceso de negociación y perfeccionamiento del contrato definitivo entre las partes. Por eso, <strong>S.O.S.srl</strong> no es responsable por el efectivo cumplimiento de las obligaciones fiscales o impositivas establecidas por la ley vigente.</p>
                    <p><strong>VII - Violaciones del Sistema o Bases de Datos</strong></p>
                    <p>No está permitida ninguna acción o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de <strong>S.O.S.srl</strong> como en las ofertas, descripciones, cuentas o bases de datos de <strong>S.O.S.srl</strong> Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, así como lo hará responsable de indemnizar los daños ocasionados.</p>
                    <p><strong>VIII - Sanciones. Suspensión de operaciones</strong></p>
                    <p>Sin perjuicio de otras medidas, <strong>S.O.S.srl</strong> podrá advertir, suspender en forma temporal o inhabilitar definitivamente la Cuenta de un Usuario o una publicación, aplicar una sanción que impacte negativamente en la reputación de un Usuario, iniciar las acciones que estime pertinentes y/o suspender la prestación de sus Servicios si (a) se quebrantara alguna ley, o cualquiera de las estipulaciones de los Términos y Condiciones Generales y demás políticas de <strong>S.O.S.srl</strong>; (b) si incumpliera sus compromisos como Usuario; (c) si se incurriera a criterio de <strong>S.O.S.srl</strong> en conductas o actos dolosos o fraudulentos; (d) no pudiera verificarse la identidad del Usuario o cualquier información proporcionada por el mismo fuere errónea; (e) <strong>S.O.S.srl</strong> entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el Usuario que las publicó, para <strong>S.O.S.srl</strong> o para los Usuarios. En el caso de la suspensión o inhabilitación de un Usuario, todos los artículos que tuviera publicados serán removidos del sistema y en ningún caso se devolverán o bonificarán los cargos de publicación involucrados. </p>
                    <p><strong>IX - Responsabilidad</strong></p>
                    <p><strong>S.O.S.srl</strong> sólo pone a disposición de los Usuarios un espacio virtual que les permite ponerse en comunicación mediante Internet para encontrar una forma de vender o comprar servicios o bienes. <strong>S.O.S.srl</strong> no es el propietario de los artículos ofrecidos, no tiene posesión de ellos ni los ofrece en venta. <strong>S.O.S.srl</strong> no interviene en el perfeccionamiento de las operaciones realizadas entre los Usuarios ni en las condiciones por ellos estipuladas para las mismas, por ello no será responsable respecto de la existencia, calidad, cantidad, estado, integridad o legitimidad de los bienes ofrecidos, adquiridos o enajenados por los Usuarios, así como de la capacidad para contratar de los Usuarios o de la veracidad de los Datos Personales por ellos ingresados. Cada Usuario conoce y acepta ser el exclusivo responsable por los artículos que publica para su venta y por las ofertas y/o compras que realiza.</p>
                    <p>Debido a que <strong>S.O.S.srl</strong> no tiene ninguna participación durante todo el tiempo en que los artículos se publican para la venta, ni en la posterior negociación y perfeccionamiento del contrato definitivo entre las partes, no será responsable por el efectivo cumplimiento de las obligaciones asumidas por los Usuarios en el perfeccionamiento de la operación. El Usuario conoce y acepta que al realizar operaciones con otros </p>
                    <p>Usuarios o terceros lo hace bajo su propio riesgo. En ningún caso <strong>S.O.S.srl</strong> será responsable por lucro cesante, o por cualquier otro daño y/o perjuicio que haya podido sufrir el Usuario, debido a las operaciones realizadas o no realizadas por artículos publicados a través de <strong>S.O.S.srl</strong></p>
                    <p><strong>S.O.S.srl</strong> recomienda actuar con prudencia y sentido común al momento de realizar operaciones con otros Usuarios. El Usuario debe tener presentes, además, los riesgos de contratar con menores o con personas que se valgan de una identidad falsa. <strong>S.O.S.srl</strong> NO será responsable por la realización de ofertas y/o operaciones con otros Usuarios basadas en la confianza depositada en el sistema o los Servicios brindados por <strong>S.O.S.srl</strong></p>
                    <p>En caso que uno o más Usuarios o algún tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a <strong>S.O.S.srl</strong> y a sus directores, gerentes, empleados, agentes, operarios, representantes y apoderados.</p>
                    <p><strong>X - Alcance de los servicios de <strong>S.O.S.srl</strong></strong></p>
                    <p>Este acuerdo no crea ningún contrato de sociedad, de mandato, de franquicia, o relación laboral entre <strong>S.O.S.srl</strong> y el usuario. El usuario reconoce y acepta que <strong>S.O.S.srl</strong> no es parte en ninguna operación, ni tiene control alguno sobre la calidad, seguridad o legalidad de los artículos anunciados, la veracidad o exactitud de los anuncios, la capacidad de los Usuarios para vender o comprar artículos. <strong>S.O.S.srl</strong> no puede asegurar que un usuario completará una operación ni podrá verificar la identidad o datos personales ingresados por los usuarios. <strong>S.O.S.srl</strong> no garantiza la veracidad de la publicidad de terceros que aparezca en el sitio y no será responsable por la correspondencia o contratos que el usuario celebre con dichos terceros o con otros usuarios.</p>
                    <p><strong>XI - Fallas en el sistema</strong></p>
                    <p><strong>S.O.S.srl</strong> no se responsabiliza por cualquier daño, perjuicio o pérdida al usuario causados por fallas en el sistema, en el servidor o en Internet. <strong>S.O.S.srl</strong> tampoco será responsable por cualquier virus que pudiera infectar el equipo del usuario como consecuencia del acceso, uso o examen de su sitio web o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audio contenidos en el mismo. Los usuarios NO podrán imputarle responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades técnicas o fallas en los sistemas o en Internet. <strong>S.O.S.srl</strong> no garantiza el acceso y uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no estar disponible debido a dificultades técnicas o fallas de Internet, o por cualquier otra circunstancia ajena a <strong>S.O.S.srl</strong>; en tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele algún tipo de responsabilidad. <strong>S.O.S.srl</strong> no será responsable por ningún error u omisión contenidos en su sitio web.</p>
                    <p><strong>XII - Tarifas. Facturación</strong></p>
                    <p>La registración en <strong>S.O.S.srl</strong> es gratuita. El sistema posee un contador de puntos (el cual el usuario puede ver en su pantalla), que sumará cada vez que el usuario vendedor acepte responder una consulta o pedido de parte del comprador. Asimismo S.O.S. srl facturará una tarifa por la publicidad y/o links que deriven en sus sitios y/o por cualquier otro servicio que se haya establecido entre las partes.Por la utilización de los Servicios, el usuario vendedor deberá pagar una tarifa ("Tarifa") a <strong>S.O.S.srl</strong> que corresponderá al valor resultante del cuadro tarifario de acuerdo al rango de consultas efectuado en el último mes de cierre.  Se realizarán los cierres de facturación el último día hábil del mes debiéndose abonar la factura entre 1 y 5 del próximo mes al cierre <strong>S.O.S.srl</strong> se reserva el derecho de modificar, cambiar, agregar, o eliminar las tarifas vigentes, en cualquier momento, lo cual será notificado a los Usuarios, en la forma establecida en la Cláusula 3. Sin embargo, <strong>S.O.S.srl</strong> podrá modificar temporalmente la Política de Tarifas y las tarifas por sus servicios por razón de promociones, siendo efectivas estas modificaciones cuando se haga pública la promoción o se realice el anuncio. </p>
                    <p><strong>S.O.S.srl</strong> se reserva el derecho de tomar las medidas judiciales y extrajudiciales que estime pertinentes para obtener el pago del monto debido.</p>
                    <p>En caso de haberse facturado cargos que no hubiesen correspondido, el usuario deberá comunicarse con nuestro equipo de Atención al Cliente para resolver dicha cuestión</p>
                    <p><strong>XIII - Propiedad intelectual. Enlaces</strong></p>
                    <p>Los contenidos de las pantallas relativas a los servicios de <strong>S.O.S.srl</strong> como así también los programas, bases de datos, redes, archivos que permiten al Usuario acceder y usar su Cuenta, son de propiedad de <strong>S.O.S.srl</strong> y están protegidas por las leyes y los tratados internacionales de derecho de autor, marcas, patentes, modelos y diseños industriales. El uso indebido y la reproducción total o parcial de dichos contenidos quedan prohibidos, salvo autorización expresa y por escrito de <strong>S.O.S.srl</strong></p>
                    <p>El Sitio puede contener enlaces a otros sitios web lo cual no indica que sean propiedad u operados por <strong>S.O.S.srl</strong>. En virtud que <strong>S.O.S.srl</strong> no tiene control sobre tales sitios, NO será responsable por los contenidos, materiales, acciones y/o servicios prestados por los mismos, ni por daños o pérdidas ocasionadas por la utilización de los mismos, sean causadas directa o indirectamente. La presencia de enlaces a otros sitios web no implica una sociedad, relación, aprobación, respaldo de <strong>S.O.S.srl</strong> a dichos sitios y sus contenidos.</p>
                    <p><strong>XIV - Indemnización</strong></p>
                    <p>El usuario acepta indemnizar y eximir de responsabilidad a <strong>S.O.S.srl</strong> (incluyendo pero no limitando a sus sociedades relacionadas, sus respectivos directores, gerentes, funcionarios, representantes, agentes y empleados) por cualquier reclamo o demanda (incluidos los honorarios razonables de abogados) formulados por cualquier Usuario y/o tercero por cualquier infracción a los Términos y Condiciones de Uso y demás Anexos y Políticas que se entienden incorporadas al presente, y/o cualquier ley y/o derechos de terceros.</p>
                    <p><strong>XV - Jurisdicción y Ley Aplicable</strong></p>
                    <p>Este acuerdo estará regido en todos sus puntos por las leyes vigentes en la República Argentina.</p>
                    <p>Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretación, alcance o cumplimiento, será sometida al arbitraje del Centro Empresarial de Mediación y Arbitraje, de acuerdo con la reglamentación vigente de dicho tribunal. La sede de dicho arbitraje será la Ciudad Autónoma de Buenos Aires y los procedimientos se llevarán a cabo en idioma castellano.</p>
                    <p><strong>XVI - Domicilio</strong></p>
                    <p>Se fija como domicilio de <strong>S.O.S.srl</strong>. la calle Lavalle 556 Piso 5 Of.1, Capital Federal, código postal 1047, República Argentina.</p>
                </div>
            </div>

        return contains;
    },
    componentWillMount:function () {
        $(document).ready(function () {
            document.body.style.backgroundColor = "#e6e0d0";
        })
    },
})
module.exports=Agreement;